[mypy]
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
explicit_package_bases = true
files = src
mypy_path = src
warn_return_any = true
warn_unused_ignores = true