from typing import Protocol


class GameAdapter(Protocol):
    async def close(self) -> None: ...

    async def input_submit_guess(self, word: str) -> None: ...

    async def check_result(self, word_index: int) -> None: ...

    async def fetch_row_result(self, row_index: int) -> list[str]: ...
